# Generated by Django 4.1.13 on 2024-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
