# Generated by Django 4.1.13 on 2024-12-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sanpham_anh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='anh',
            new_name='image',
        ),
    ]
