# Generated by Django 4.1.13 on 2024-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_anh_sanpham_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sanpham_images/'),
        ),
    ]
