# Generated by Django 4.1.13 on 2024-12-07 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_alter_sanpham_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dathang',
            old_name='luu_thong_tin_dat_hang_id',
            new_name='ma_dat_hang',
        ),
        migrations.RenameField(
            model_name='datnhieuhang',
            old_name='ngay_dat_hang',
            new_name='ngay_tao',
        ),
        migrations.RenameField(
            model_name='diachigiaohang',
            old_name='ngay_dat_hang',
            new_name='ngay_tao',
        ),
        migrations.AlterField(
            model_name='datnhieuhang',
            name='dat_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dathang'),
        ),
        migrations.AlterField(
            model_name='datnhieuhang',
            name='san_pham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sanpham'),
        ),
        migrations.AlterField(
            model_name='diachigiaohang',
            name='dat_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dathang'),
        ),
        migrations.AlterField(
            model_name='diachigiaohang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.khachhang'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
